services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            postgres:
                condition: service_started

    postgres:
        build:
                context: .
                dockerfile: Dockerfile.postgres
        restart: always
        volumes:
                - postgres_data:/var/lib/postgresql/data
        environment:
                - POSTGRES_DB=postgres
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres

volumes:
    postgres_data:
        driver: local