FROM mirror.gcr.io/postgres:11.5

USER postgres

COPY backend/database/init_db.sql /docker-entrypoint-initdb.d/init_db.sql

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 5432

CMD ["postgres"]                                                                